### ISSUE TITLE
CloudFormation Template is Failed 

### ISSUE THREAD

**Issue by st3930** [awslabs/workload-discovery-on-aws#311]
If your issue relates to the _Discovery Process_, please first follow the steps described in the implementation guide [Debugging the Discovery Component](https://docs.aws.amazon.com/solutions/latest/aws-perspective/appendix-e-debugging-the-discovery-component.html)

---

**Describe the bug**
When Set  "AlreadyHaveConfigSetup" to "No", CloudFormation is fail. Because ConfigRole Policy name is changed from AWSConfigRole to AWS_ConfigRole Since July 5, 2022.
If Set  "AlreadyHaveConfigSetup" to "Yes" after AWS Config is available, CloudFormation is success.
https://aws.amazon.com/jp/blogs/mt/service-notice-upcoming-changes-required-for-aws-config/

workload-discovery-on-aws/source/cfn/templates/zoom-import-and-aggregator.yaml
```
  ConfigRole:
    Type: AWS::IAM::Role
    Condition: SetUpConfig
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - config.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSConfigRole <- This!!
```

**To Reproduce**

**Expected behavior**
A description of what you expected to happen.

**Screenshots**

**Browser (please complete the following information):**

- Name [e.g. chrome, firefox]

**Additional context**
