### ISSUE TITLE
NeptuneStack failed to create

### ISSUE THREAD

**Issue by s4kharitonov** [awslabs/workload-discovery-on-aws#320]
If your issue relates to the _Discovery Process_, please first follow the steps described in the implementation guide [Debugging the Discovery Component](https://docs.aws.amazon.com/solutions/latest/aws-perspective/appendix-e-debugging-the-discovery-component.html)

---

**Describe the bug**
Creation of WDNeptuneDBCluster failed

The Parameter Group workload-discovery-neptune-cluster-parameter-group with DBParameterGroupFamily neptune1 cannot be used for this instance. Please use a Parameter Group with DBParameterGroupFamily neptune1.2 (Service: AmazonNeptune; Status Code: 400; Error Code: InvalidParameterCombination; Request ID: 43e211aa-5f07-40a6-af07-4ffc2d3b6f87; Proxy: null)

**To Reproduce**

Run main.template

**Expected behavior**
NeptuneStack created successful

**Comment by svozza** [comment]
We are currently working on releasing a fix for this. As a workaround, you can edit the `Family` field to `neptune1.2` in the template linked below to continue:

https://github.com/awslabs/workload-discovery-on-aws/blob/c87dfe411593dea905e36deceac2d31fee396657/source/cfn/templates/neptune.template#L391

https://github.com/awslabs/workload-discovery-on-aws/blob/c87dfe411593dea905e36deceac2d31fee396657/source/cfn/templates/neptune.template#L425

**Comment by dieherna** [comment]
Svozza I have been trying to figure out exactly how to implement the provided however I am not having much luck. When you import the Cloudformation template I don’t see an option to be able to edit the nested neptune.template. I have also tried uploading the contents of the cfn folder from this github to my own S3 bucket and then tried deploying the main.template after modifying neptune.template but then the stack fails to build as it looks like it doesn’t resolve the variables in main.template. Also I notice there are some zip files that some of the other templates are referencing.

Any guidance you can provide is much appreciated.

**Comment by svozza** [comment]
The esiest way to get it working is the do a local build. Clone the repo, make the changes to the template and follow the instructions here: https://github.com/awslabs/workload-discovery-on-aws#deploying-a-local-build.

**Comment by s4kharitonov** [comment]
**Local build**

Failed on TaskStack stack
```
  TaskStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Sub
          - ${DeploymentBucket}/discovery-crawler.template
          - DeploymentBucket: !GetAtt Variables.DeploymentBucket
      TimeoutInMinutes: 60
      Parameters:
        DiscoveryBucket: !GetAtt S3Buckets.Outputs.DiscoveryBucket
        AppName: !FindInMap [Solution, Constants, AppName]
        PrivateSubnet0: !GetAtt VpcStack.Outputs.PrivateSubnet0
        PrivateSubnet1: !GetAtt VpcStack.Outputs.PrivateSubnet1
        VpcId: !GetAtt VpcStack.Outputs.VPCId
        VpcEndpointsSg: !GetAtt VpcStack.Outputs.VpcEndpointsSg
        ImageVersion: !FindInMap [Solution, Constants, ImageVersion]
        ConfigurationAggregator: !GetAtt ConfigAggregator.Outputs.PerspectiveConfigurationAggregator
        AppSyncArn: !GetAtt AppSyncApiStack.Outputs.AppSyncApiArn
        AppSyncApiUrl: !GetAtt AppSyncApiStack.Outputs.AppSyncApiUrl
        Cpu: 1024
        Memory: 2048
        Decorators: !GetAtt LayerStack.Outputs.Decorators
        BotoUtils: !GetAtt LayerStack.Outputs.BotoUtils
        CustomResourceHelper: !GetAtt LayerStack.Outputs.CustomResourceHelper
        DeploymentBucketName: !GetAtt Variables.DeploymentBucketName
        DeploymentBucketKey: !FindInMap [ Solution, Constants, DeploymentBucketKey ]
```
Template: discovery-crawler.template
```
  CleanupECRRepository:
    Type: Custom::Setup
    Properties:
      ServiceToken: !GetAtt CleanupRepositoryFunction.Arn
      LogLevel: !Ref LogLevel
      Repository: !Ref PerspectiveContainerRepo
```

![img-2022-11-23-13-56-01](https://user-images.githubusercontent.com/33975462/203532017-12e31050-5f6d-4d81-9e9b-cfd1f40b856b.png)
